" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

set runtimepath&
set runtimepath+=~/projects/vim-autocomplpop,~/projects/vim-fuzzyfinder,~/projects/dotfiles/vim/runtime,~/projects/dotfiles/vim/runtime/after

filetype plugin indent on
syntax enable

source ~/projects/dotfiles/vim/abbreviations.vim
source ~/projects/dotfiles/vim/autocmds.vim
source ~/projects/dotfiles/vim/customcommands.vim
source ~/projects/dotfiles/vim/mappings.vim
source ~/projects/dotfiles/vim/options.vim
source ~/projects/dotfiles/vim/pluginsettings.vim
source ~/projects/dotfiles/vim/utils.vim
